### ISSUE TITLE
motionblinds.motion_blinds device has status '6' that is not yet known

### ISSUE THREAD

**Issue by nagypeeter** [starkillerOG/motion-blinds#10]
2021-06-15 14:42:51 ERROR (SyncWorker_10) [motionblinds.motion_blinds] Device with mac 'xxx' has status '6' that is not yet known, please submit an issue at https://github.com/starkillerOG/motion-blinds/issues.

**Comment by starkillerOG** [comment]
@nagypeeter thank you for reporting.
I already new about the status "6", it is a bug in the firmware of the bridge.
The product developers will remove this in a new version of the firmware of the bridge.
I will in the meantime add status "6" as "firmware_bug" to avoid this error warning poping up.

**Comment by sygys** [comment]
You say you did something so this error (status 6) wouldnt show up anymore but just got the error today. So isnt this fixed as of june? or is this a new error?

**Comment by starkillerOG** [comment]
The PR with the fix has not yet been merged: https://github.com/home-assistant/core/pull/50067
It is still waiting on a revieuw from the core team.

**Comment by sygys** [comment]
No problem, i guees this error has no effect on the use of the blinds (curtain)?

**Comment by starkillerOG** [comment]
yes you are correct.
