### ISSUE TITLE
Issue Brel Hub

### ISSUE THREAD

**Issue by Rustynl** [starkillerOG/motion-blinds#15]
I am trying to add my brel hub to the motion blind integration, but I am getting an unknown error has occured.
I am thinking it might have to do with my google wifi not (fully) supporting multicast, can you let me know if this error is indeed caused by that?

`Logger: motionblinds.motion_blinds
Source: /usr/local/lib/python3.9/site-packages/motionblinds/motion_blinds.py:797
First occurred: 11:59:45 AM (13 occurrences)
Last logged: 2:47:51 PM

Device with mac '98f4ab8850240001' send an response with unexpected data, please submit an issue at https://github.com/starkillerOG/motion-blinds/issues. Response: '{'msgType': 'ReadDeviceAck', 'mac': '98f4ab8850240001', 'deviceType': '10000000', 'msgID': '20211005115555295', 'data': {'type': 6, 'operation': 1, 'wirelessMode': 0}}', Exception: ''RSSI''
Device with mac '98f4ab8850240001' send an response with unexpected data, please submit an issue at https://github.com/starkillerOG/motion-blinds/issues. Response: '{'msgType': 'ReadDeviceAck', 'mac': '98f4ab8850240001', 'deviceType': '10000000', 'msgID': '20211005115956709', 'data': {'type': 6, 'operation': 1, 'wirelessMode': 0}}', Exception: ''RSSI''
Device with mac '98f4ab8850240001' send an response with unexpected data, please submit an issue at https://github.com/starkillerOG/motion-blinds/issues. Response: '{'msgType': 'ReadDeviceAck', 'mac': '98f4ab8850240001', 'deviceType': '10000000', 'msgID': '20211005100134792', 'data': {'type': 6, 'operation': 2, 'wirelessMode': 0}}', Exception: ''RSSI''
Device with mac '98f4ab8850240001' send an response with unexpected data, please submit an issue at https://github.com/starkillerOG/motion-blinds/issues. Response: '{'msgType': 'ReadDeviceAck', 'mac': '98f4ab8850240001', 'deviceType': '10000000', 'msgID': '20211005131258919', 'data': {'type': 6, 'operation': 2, 'wirelessMode': 0}}', Exception: ''RSSI''`

**Comment by starkillerOG** [comment]
@Rustynl this does not look like an issue with the multicast, this is probably due to the unidirection-blind not yet beeing supported in your HomeAssistant version.
The new HomeAssistant version that schould come out today (2021.10.0) schould have support for unidirection-blinds, however it has not yet been tested, so please report back here if it works with the new HomeAssistant version.

Besides it would be really helpfull if you could test this library directly with your brel hub:
If you have python3 installed on some PC (operating system does not matter, can be windows), go to the command line of that PC and use: `pip3 install --upgrade motionblinds` to install this library.

Then execute the following python script, filling in your gateway IP and key:

```
from motionblinds import MotionGateway
m = MotionGateway(ip = "192.168.1.100", key = "12ab345c-d67e-8f")

m.GetDeviceList()
m.Update()

for blind in m.device_list.values():
    blind.Update()
    print(blind)
```

**Comment by Rustynl** [comment]
I tried to run the script (first time I am using Python, so possible I am doing something wrong) and I am getting the following (*’s are replacing my username):

 

Traceback (most recent call last):

  File "c:\Users\*****\AppData\Local\Programs\Python\Python310\Lib\motion.py", line 8, in <module>

    blind.Update()

  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\motionblinds\motion_blinds.py", line 922, in Update

    mcast = self._gateway._create_mcast_socket('any', False)

  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\motionblinds\motion_blinds.py", line 125, in _create_mcast_socket

    udp_socket.setsockopt(

OSError: [WinError 10022] An invalid argument was supplied

**Comment by Rustynl** [comment]
I tried to run the script (first time I am using Python, so possible I am doing something wrong) and I am getting the following (*’s are replacing my username):

```
Traceback (most recent call last):
  File "c:\Users\*****\AppData\Local\Programs\Python\Python310\Lib\motion.py", line 8, in <module>
    blind.Update()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\motionblinds\motion_blinds.py", line 922, in Update
    mcast = self._gateway._create_mcast_socket('any', False)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\motionblinds\motion_blinds.py", line 125, in _create_mcast_socket
    udp_socket.setsockopt(
OSError: [WinError 10022] An invalid argument was supplied
```

**Comment by starkillerOG** [comment]
@Rustynl I think this PR will fix the greyed out button: https://github.com/home-assistant/core/pull/57266
The error above is something to do with windows, but as it is working with your homeassistant I will leave that as is.

Do you also still see the slide bar for the position selection?

**Comment by Rustynl** [comment]
Once the PR gets added to HA I will let you know.
I dont think it was in any of the updates of the last few days.

If you want I can still try to figure out why I get that Python error. Happy to help if it helps you.

I do not see a slide bar for position selection, only open, stop and close.

**Comment by Rustynl** [comment]
It is all working now, thanks!

I will have an other look at running the python script this weekend, I am running it in Python3. 
But I just installed and ran it, never ran anything else before. Will do some digging and let you know.

**Comment by starkillerOG** [comment]
@Rustynl Great to hear it is now working.
Thanks for your effort.
