### ISSUE TITLE
New Blind Type - 27

### ISSUE THREAD

**Issue by ArmoredCavalry** [starkillerOG/motion-blinds#22]
I got the motion-blind integration up and running, but saw this error in logs with a message to open an issue -

`blind_type '27' that is not yet known`

Here is a link to the product - https://www.altawindowfashions.com/product/dual-shades/

Let me know if I can provide any other info!

**Comment by starkillerOG** [comment]
This looks very simular to the dubbelroller of motion blinds.
Is it true that the phone application has a seperate slider/tilt for controlling how much light passes through (besides the position of the whole blind)?

**Comment by ArmoredCavalry** [comment]
Yes I believe that's correct. Here's a ![screenshot](https://user-images.githubusercontent.com/18032892/163267774-4be0412b-d187-4885-90bb-5697e07f7bdb.png)

**Comment by starkillerOG** [comment]
The HomeAssistant PR to fully support the Dual Shade is here: https://github.com/home-assistant/core/pull/70019
That will also add the tilt controls.

**Comment by starkillerOG** [comment]
Dual Shade support will be in HomeAssistant 2022.05 which will be released May 4th.
Please let me know if it works correctly on version 2022.05

**Comment by starkillerOG** [comment]
Since HomeAssistant 2022.05 is released I will close this issue.
@ArmoredCavalry If you experiance any other issues, please let me know.
If you appriciate the Motion Blinds integration, consider sponsoring this library.
