### ISSUE TITLE
Additional Brand Support - Discoverability

### ISSUE THREAD

**Issue by ArmoredCavalry** [starkillerOG/motion-blinds#23]
Found that the BLISS Automation / Alta brand shades work great with motion-blinds integration, luckily stumbled on this thread about it - https://community.home-assistant.io/t/dooya-rf-blinds-controlling-with-receiving-sending-signals/193840/7

Looks like if you go to the FAQ tab on this page, has an up-to-date list of the brands it works with - https://chowmain.software/drivers/control4-dooya

I saw there is a list on the Readme for the project, and in the HA documentation, is there any way this information could be raised to the integration search level in Home Assistant for Discoverability? Maybe this is more an HA issue, but perhaps "aliases" for an integration name?

**Comment by starkillerOG** [comment]
The Readme of this project has been updated, closing this issue.
Thanks again!

Feel free to open a new issue if you have additional questions/problems!

**Comment by ArmoredCavalry** [comment]
Thanks for updating! As suggested, I've opened a discussion on a possible new HA feature for integration aliases / search update - https://github.com/home-assistant/frontend/discussions/12328
