### ISSUE TITLE
Home assistant integration

### ISSUE THREAD

**Issue by aboogerd** [starkillerOG/motion-blinds#3]
Hi starkillerOG, 

First of all kudos for your work integrating motion blinds to Home Assistant.

Don't know if this is the right place to ask. But when the screen is open/up the slider is 100% and closed/down 0%. Is this correct/normal?

The use of the arrows in HA is working correctly.

Cheers, Alexander

**Comment by starkillerOG** [comment]
Thanks!

Yes open/up=100% en closed/down=0%, this is standardized in HomeAsisstant and works that way for all covers within HA. (It is also documented in the dev docs) 

For the latest improvements see this open PR: https://github.com/home-assistant/core/pull/43656

Feel free to open up another issue if you experience any other problems.

Best regards,
StarkillerOG
