### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ShadowShadow42** [starkillerOG/motion-blinds#30]
Hi starkillerOG,
I have a question for you but don't know how I can best contact you. I've send an email to starkiller.og@gmail dot com, but don't know if that email adress works at all. Can you please reply. 

Many thanks,
Rein

**Comment by starkillerOG** [comment]
Hi Rein,

I send you a reply by mail.
Normally I do not read starkiller.og@gmail.com but do get messages from github.

Best regards,
StarkillerOG
