### ISSUE TITLE
Is a brel hub necessary on wifi motors?

### ISSUE THREAD

**Issue by sliverlin** [starkillerOG/motion-blinds#35]
Is a brel hub necessary on wifi motors?
This integration allows for directly controlling blinds that support wifi-connection
but I must enter a gateway ip for the configuration
is the way I use it wrong?

**Comment by starkillerOG** [comment]
@sliverlin no a hub is not necessary on wifi motors.
Just put in the IP of the wifi motor in the field of the gateway ip.
(In case of a wifi motor the motor is the gateway).

Let me know if you have any other problems setting up the integration.

If you appreciate the motion blinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.
