### ISSUE TITLE
Curtain shows battery level of 9%

### ISSUE THREAD

**Issue by PRoomberg** [starkillerOG/motion-blinds#37]
I've added two MotionBlind Curtains to my setup. They work fine with this library, except for the battery level.
That is always shown as 9%, even if the batteries are full.

Here's output from:
 
```
for blind in m.device_list.values():
     blind.Update()
     print(blind)
```

```
<MotionBlind mac: abababababd0001, type: RollerBlind, status: Stopped, position: 0 %, angle: 0.0, limit: Limit3Detected, battery: DC, 33.0 %, 6.93 V, charging: None, RSSI: -102 dBm, com: BiDirection>
<MotionBlind mac: abababababd0002, type: RollerBlind, status: Stopped, position: 0 %, angle: 0.0, limit: Limit3Detected, battery: DC, 46.0 %, 7.22 V, charging: None, RSSI: -70 dBm, com: BiDirection>
<MotionBlind mac: abababababd0003, type: RollerBlind, status: Stopped, position: 0 %, angle: 0.0, limit: BothLimitsDetected, battery: DC, 46.0 %, 7.22 V, charging: None, RSSI: -82 dBm, com: BiDirection>
<MotionBlind mac: abababababd0004, type: Curtain, status: Stopped, position: 90 %, angle: 0.0, limit: BothLimitsDetected, battery: DC, 9.0 %, 14.8 V, charging: None, RSSI: -87 dBm, com: BiDirection>
<MotionBlind mac: abababababd0005, type: Curtain, status: Stopped, position: 0 %, angle: 0.0, limit: BothLimitsDetected, battery: DC, 9.0 %, 14.8 V, charging: None, RSSI: -89 dBm, com: BiDirection>
```

**Comment by starkillerOG** [comment]
@PRoomberg what model and brand curtain motor is it?
Is it from Motion Blinds itself or some other brand also supported?

Does the battery percentage change and go to negative numbers over time?

Unfortunetly Motion Blinds motors only report the battery voltage: 14.8V in your case for the curtain motors.
To get a percentage I have to assume standard battery packs from Motion Blinds:
# 2 cel battery pack (8.4V when fully charged, 6.2 when empty)
# 3 cel battery pack (12.6V when fully charged, 10.4 when empty tested 10.27-12.34V)
# 4 cel battery pack (16.8V when fully charged, 14.6 when empty)

If your motor battery pack uses a diffrent range of voltages the percentage shown will be wrong.

In homeassistant the battery sensor entity also has an attribute which shows you the voltage.
You can use that in a template entity to make your own battery percentage sensor where you can specify the fully charged and empty voltages like this:
`{{((state_attr('sensor.office_shade_battery', 'battery_voltage')|default(10.27, true) - 10.27) * 100 / (12.34 - 10.27))|round(1)}}`
Where you need to change the `sensor.office_shade_battery` to your entity ID and adjust the fully charged voltage (12.34) and fully empty voltage (10.27).

In your case the fully charged voltage is apperently 14.8 V, the empty voltage you will need to look up in the manual or just use the curtain motors untill they stop working and see what the battery voltage is then.

If you appreciate the motion blinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) this library.

**Comment by PRoomberg** [comment]
It's a curtain rail from Motion Blinds themself and it uses the CM-36 motor.
<img width="1246" alt="CM-36" src="https://github.com/starkillerOG/motion-blinds/assets/73638628/ca95d44e-e0b2-4441-b280-675ec61a3732">
Looks like these use a different battery pack then the 2-3-4 cell packs.

I've been using two of these for a month now with daily usage and they still show 14.8 volts.
Thanks for the tip for home assistant. I use Indigo instead and created my own plugin for MotionBlinds support.
I'll think about adding an algorithm to convert the voltage to a battery %.
