### ISSUE TITLE
Unknown brel type 57

### ISSUE THREAD

**Issue by Pipsen94** [starkillerOG/motion-blinds#39]
Hi.

I have this error.

Device with mac '4c75251360800001' has blind_type '57' that is not yet known, please submit an issue at https://github.com/starkillerOG/motion-blinds/issues

It´s a brel triangle bleated blind. Work and recognized ind the brel app.

But in HA is unknown This device has no entities

Can you help? 

Many thanks.

**Comment by starkillerOG** [comment]
@Pipsen94 thanks for reporting this.
I think it is this motor right?: https://www.brel-home.nl/en/pro/products/bi-directional-motors/641/bje24tr-0-634

How do you opperate this blind in the brel app?
Do you only have up/down position control or do you also have tilt control with this motor?

**Comment by starkillerOG** [comment]
Eventhough the blindtype is not yet known, it should have gave the warning: `"Blind type '%s' not yet supported, assuming RollerBlind"` and added it as a rollerblind....

Do you see any additional warnings/errors?

**Comment by Pipsen94** [comment]
@starkillerOG 

Thank you very much for your time.

I'm pretty sure it's a correct motor that you've found.

Just reinstalled motion blinds integration and added API key from brel app again now.

I have attached some pictures from the brel app (so you can see what the control looks like) and the log from the HA.
Also attached a picture from a working blind and a picture from the unknown.

I have two regular up/down roller blinds also from brel which it finds and has the functions (up/down - stop) immediately.

The other blinds that are with the motor you link to, it says unknown and have no options to control it in the integration.

Hope you can help :)

Best wishes.


[home-assistant_2024-02-04T17-13-52.682Z.log](https://github.com/starkillerOG/motion-blinds/files/14157674/home-assistant_2024-02-04T17-13-52.682Z.log)
![HA motion blinds integration - Roller blind with controls](https://github.com/starkillerOG/motion-blinds/assets/155903969/6ff3071d-b651-47d7-99d0-0dd713133591)
![HA motion blinds integration - unknown device](https://github.com/starkillerOG/motion-blinds/assets/155903969/612eb3f5-b1e3-4efe-aba5-b0b7ef2c5824)
![HA motion blinds integration](https://github.com/starkillerOG/motion-blinds/assets/155903969/cebcd94c-d367-4a61-af08-c3ff873a0ae1)
![Brel app3](https://github.com/starkillerOG/motion-blinds/assets/155903969/ac1ecfd1-68eb-4c2e-8f2b-0a389bfca947)
![Brel app2](https://github.com/starkillerOG/motion-blinds/assets/155903969/b7d109bf-b005-4d01-a89f-2bbb8e2c1141)
![Brel app1](https://github.com/starkillerOG/motion-blinds/assets/155903969/a74e60e0-55c2-4dc9-8006-5254419df4fc)

**Comment by starkillerOG** [comment]
@Pipsen94 thank you very much for the debug log, that is extremely helpfull!!!

This motor behaves like a TopDownBottomUp and is more complicated than the standard RollerBlinds.
Since the type is unknown, a RollerBlind is assumed causing errors and the entities not to show up.

I can make it work, but first I will need to know exactly how this thing behaves.
Apperently there are two motors in this thing.
But are you allowed to change both motors independently?
With a normal TopDownBottomUp that is the case.

But with this one I believe you first have to fully close the bottom motor before you are allowed to operate the top motor....
In your pictures I see 100, 30% or 100, 100%.
Could you play a bit with the motor and see what combinations are possible?
Is 0, 0% possible?
100, 0?
0, 100?
50, 50?

How do these percentages change when moving the motor from fully down to halfway straight piece up, to straight piece fully up, to halfway triangle piece up, to triangle piece fully up?

**Comment by starkillerOG** [comment]
Is it possible to close the straigt part while opening the triangle part?

**Comment by Pipsen94** [comment]
@starkillerOG 

No I can only control the bottom "straigt" part when the triangle part is fully closed and the other way around.
I can only control the triangle part when the bottom part is fully closed.

So in the brel app - I can do:

0 % - 0 % the blinds are fully open.
50 % - 0 % the triangle part is half closed.
100 % - 0 % the triangle part is fully closed.
100 % - 50 % the triangle part is fully closed and the straigt part is half closed
100 % - 100 % all closed

**Comment by starkillerOG** [comment]
@Pipsen94 thank you for the info, that makes it a lot more insightfull for me.

I will do some additional coding to get this type of blind supported. Unfortunately it has a unique way of control.
Therefore this requires quite a lot of new code, it can probably not be included in a patch release. Therefore it will be included at the earliest in HA 2023.3.0

I will make some code this week, maybe I will let you test it as a custom component.

If you appreciate the motion blinds integration and want to support its development, please consider sponsering this library.

**Comment by Pipsen94** [comment]
@starkillerOG 

thank you very much. If it becomes necessary, just write to me regarding possible testing. a donation will definitely happen for all your fantastic work.

**Comment by Pipsen94** [comment]
@starkillerOG 

Hi again :)

Thanks for the quick reply.

The curtain is now visible in integration and there are 3 rows of controls. I have attached a picture of it.

The first row controls the triangle part of the curtain and the second row the bottom part.

I don't quite sure about the third row of control does? When I push the arrow up, only the lower part of the curtain opens and stops when the bottom part is closed. When I push down, it goes down a little before going all the way back up.

I was wondering if it is possible to code it so that you can open/close the whole thing (both the triangle part and bottom part) with one push of a button?

Right now, in the brel app as well as the physical remote control, I can open and close from top to bottom and vice versa.

Thanks.

I have attached a picture of the blind when is fully closed and one with the bottom open. Also a small video showing what happens when I push down on the third row of controls

https://github.com/starkillerOG/motion-blinds/assets/155903969/ee0413ec-6daa-4f39-b742-66c823c51969

![IMG_1505](https://github.com/starkillerOG/motion-blinds/assets/155903969/d6df1372-3255-4125-892e-7670eeb7cb77)
![IMG_1506](https://github.com/starkillerOG/motion-blinds/assets/155903969/6fe7887d-8d66-421d-a9b4-28410ce69f98)
![Test 1](https://github.com/starkillerOG/motion-blinds/assets/155903969/904f8fbd-4989-48e5-a80f-60a7e720abd2)

**Comment by starkillerOG** [comment]
So first of all the naming is not correct apperently...
It schould have added Bottom, Top and Combined to the names, I will check that.
I will also adjust the way up/down are handeled.

**Comment by Pipsen94** [comment]
@starkillerOG 

thank you will test it again when you have a change to look at it.

**Comment by starkillerOG** [comment]
@Pipsen94 This PR will hopefully fix the control of the combined entity: https://github.com/home-assistant/core/pull/110970
The PR to fix the naming (Top, Bottom, Combined) has already been merged.
Both PRs are tagged for the HA 2023.2.3 patch release, so you should be able to test in a few days.

**Comment by Pipsen94** [comment]
@starkillerOG 

Just updated but now I have no controls available at all.

same problem on all blinds.

i have tried to reinstall also.

**Comment by starkillerOG** [comment]
@Pipsen94 I know, see PR https://github.com/home-assistant/core/pull/110871
The solution is merged, but at the last moment there was a conflict in getting it into HA 2024.2.3.
Unfortunetely this means you will have to wait for HA 2024.3.0 release that will fix this.

I am sorry.

**Comment by starkillerOG** [comment]
In the meantime you could downgrade to HA 2024.2.1, that should work for now (withouth the proper fixes for the triangle blind).

**Comment by starkillerOG** [comment]
@Pipsen94 have you already tried with HA 2023.3.0?
