### ISSUE TITLE
Nice job - have you tried getting it to work with the remotes as well?

### ISSUE THREAD

**Issue by tlobinger** [starkillerOG/motion-blinds#4]
I have this one https://motion-blinds.com/support/cm-11-hand-remote-1-channel and unable to buy a hub anymore, they seem to be out of stock. I saw the remote as the hubs have 433MHz communication channels and tried to record what they send with https://github.com/milaq/rpi-rf without success. And I did not feel like going down a rabbit hole like this one https://nickwhyte.com/post/2017/reversing-433mhz-raex-motorised-rf-blinds/ :)

hints very welcome!

**Comment by starkillerOG** [comment]
@tlobinger I have not tried intersepting the 433MHz signals.
However it will probably be quite some work to get it reliable and get a good communication set up.
I would highly recommand just buying the hub.

Personally I have this hub: https://motion-blinds.com/nl/support/motion-wifi-bridge
But it will probably also work with this hub https://www.hornbach.nl/shop/MOTION-Wi-Fi-Bridge-voor-Soluna-rolgordijnen/10251930/artikel.html that is available at Horenbach.

**Comment by tlobinger** [comment]
Thanks, they stopped selling in Germany. I will try to get one from the Netherlands.
