### ISSUE TITLE
Using motion-blinds on HA running in VBoxVM

### ISSUE THREAD

**Issue by kopasiak** [starkillerOG/motion-blinds#42]
I've a setup where HA (HAOS image) runs in a VBoxVM. I've added the support for a gate driver that I own in a new PR and I've 2 questions:

1. After this PR is merged what would be the necessary steps for me to make a component in HA use it?
2. Do you have any recommendations how to configure multicast forwarding from host to that VM?

**Comment by starkillerOG** [comment]
@kopasiak I have merged your PR, released a new version of motionblinds and made the nessesary Pull Requests in HomeAssistant: https://github.com/home-assistant/core/pull/111265
I expect those to be merged before the beta cut of Home Assistant 2023.3.0.

So all you have to do is wait untill HomeAssistant 2023.3.0 will be released and update to that version.
The motionblinds integration should then start to work with your Krispol garage gate.

I am not an expert with network setup, so unfortunetely I cant help you with configuring the multicast correctly.

If you appreciate the Motionblinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.
