### ISSUE TITLE
Cannot add Brell Hub, Unkown error occurred

### ISSUE THREAD

**Issue by epjjansen** [starkillerOG/motion-blinds#44]
Brell Bub lost connection, so after deleting hub in HA re-adding hub

Steps taken:

1. Add integration
2. Motion Blinds
3. Enter ip address of hub: 192.168.1.xx
4. Enter API Key from Brell app (16 characters)
5. Submit

result: Unknown error occured.

Hub used:
DD-7002B / HUB-02
BREL HOME Hub - WiFi RS485

Error log:

> Logger: aiohttp.server
> Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
> First occurred: February 29, 2024 at 00:23:54 (2 occurrences)
> Last logged: 09:36:48
> 
> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
>     resp = await request_handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
>     resp = await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
>     response = await handler(request)
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
>     result = await handler(request, **request.match_info)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
>     return await func(self, request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
>     return await super().post(request, flow_id)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
>     result = await method(view, request, data, *args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
>     result = await self._flow_mgr.async_configure(flow_id, data)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
>     result = await self._async_configure(flow_id, user_input)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
>     result = await self._async_handle_step(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
>     result: FlowResult = await getattr(flow, method)(user_input)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/motion_blinds/config_flow.py", line 158, in async_step_connect
>     if not await connect_gateway_class.async_connect_gateway(self._host, key):
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/motion_blinds/gateway.py", line 52, in async_connect_gateway
>     await self._hass.async_add_executor_job(self.update_gateway)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/motion_blinds/gateway.py", line 39, in update_gateway
>     self.gateway_device.GetDeviceList()
>   File "/usr/local/lib/python3.12/site-packages/motionblinds/motion_blinds.py", line 714, in GetDeviceList
>     responses = self._send(msg, single_response=False)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/motionblinds/motion_blinds.py", line 511, in _send
>     responses.append(json.loads(d))
>                      ^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/json/__init__.py", line 341, in loads
>     s = s.decode(detect_encoding(s), 'surrogatepass')
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 353: invalid start byte

**Comment by epjjansen** [comment]
![2024-02-26 16_25_28-Settings – Home Assistant](https://github.com/starkillerOG/motion-blinds/assets/68750605/d3bc1059-8306-425f-a55a-30091e451473)

**Comment by starkillerOG** [comment]
I would power cycle the Brell Hub, then try again.
Also check if the IP of the Hub did not change and check if the key did not change (in the brel app).

**Comment by epjjansen** [comment]
After resetting the Brell hub to factory defaults I could add it to Home assistant again.
Was a bit work to recreate all scenes and automations but it worked.

Thanks for showing where the issue was.

**Comment by starkillerOG** [comment]
If you appreciate the motionblinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) this library.
