### ISSUE TITLE
Brel wood shutters tilt only: position random?

### ISSUE THREAD

**Issue by rknotter** [starkillerOG/motion-blinds#46]
Hi, 

I just installed 7 Brel wood shutters, tilt only, with hub. In the app the tilt position (in degrees) is correct, from -90 to 0 (horizontal) to +90. I even finetuned the start/end positions to have a consistent response of all shutters. 

I added the Motionblinds integration with (I think) succes. In HASS I can use cover.set_cover_tilt_position, however this seems to be sort of random. For instance: if I set all covers closed (90 degr) in the Brel app and do the following: 

service: cover.set_cover_tilt_position
target:
  entity_id: cover.zonwering_beneden
data:
  tilt_position: 0

the shutters tilt end up at random positions (-36, -34, -14, -31, -18, 0 and 7 degrees). The expected behaviour would be to open completely, being -90 degr in the app. Horizontal would be 50 in HASS and 0 in the app. 

Is this a configuration issue? Or is this a bug in the integration perhaps? 

Thanks for your time!

**Comment by rknotter** [comment]
I'm sorry, this is the wrong repository.

**Comment by starkillerOG** [comment]
This has been solved in the latest HA release, therefore I will close this issue.

If you are still experiancing this issue, please let me know.
