### ISSUE TITLE
Question / RFC

### ISSUE THREAD

**Issue by d-EScape** [starkillerOG/motion-blinds#8]
How can a callback tell which blind triggered it when it is not possible to pass an argument to the callback?

If line 813 is changed from
`callback()`
to 
`callback(self)`
then the (sending) MotionBlind instance would be available to the callback. But maybe there are better ways?

**Comment by starkillerOG** [comment]
Yes you are correct, wrapping the motion blind object in a class is the way to go (at least I intended it that way).
That is also how it is done in HomeAssistant.
