### ISSUE TITLE
AccessToken error

### ISSUE THREAD

**Issue by BodingClockchian** [starkillerOG/motion-blinds#9]
Hi, im having a bit of a strange problem with the gateway. 

I have a repeating issue with the gateway randomly forgetting all its settings. Normally I would delete the gateway and add a 'new' one in the Motion app. Today it looks like the connections to the Motion servers are down. (From my network point of view)

The situation. Gateway is connected to my WiFi and has been assigned an IP-adres. Its blinking yellow which means its unable to connect to the cloud/internet servers. (Motion app says the same. Both on LTE and WiFi)

But I should be able to control the gateway/blinds despite the connection error.  (Local only)
Connection to the gateway is working
`<MotionGateway ip: 10.1.1.20, mac: 5002xxx, protocol: 0.9, N_devices: 3, status: Working, RSSI: -68 dBm>`

Connection to one of the blinds looks fine
`>>> blind_1.RSSI -74`
`>>> blind_1.battery_level 49.09`

But performing a task will resolve in 'AccessToken error'.
`>>> blind_1.Open()
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '500291xxxxx', 'deviceType': '10000000', 'AccessToken': 'D506A3E24531Cxxxxxxx', 'msgID': '20211006081914251', 'data': {'operation': 1}}'`

Do you know what is causing this AccessToken error?

**Comment by starkillerOG** [comment]
Hi @BodingClockchian.
That seems like a weard issue for the gateway forgetting its settings, I have not experianced that.
Have you contacted Motion/Coullise B.V. about this?

Actually this morning I also saw the light on my gateway blinking yellow, so I don't think it is a issue at your side but the cloud servers of Motion are actually down.

That is really intresting, I have experianced a simular issue one time when the cloud servers where down that I was unable to control the blinds (even with local commands). Maybe the AccesToken is checked internally in the gateway with the cloud, although that sounds like a really bad design if that is the case.

I checked at this moment, and I can control the blinds just fine now (@10:56 10-06-2021), but I can't check at the moment if my gateway is still blinking yellow, the servers might be up again?

**Comment by BodingClockchian** [comment]
Hi, no I still have to contact Motion/Coullise B.V. about the reset issue.

The whole Motion app / cloud connected devices is a really bad idea. This accesstoken issue is the perfect example why you should not buy cloud connected devices. Still blinking yellow btw (@11:23 10-06-2021)

Is there a way to update the underlaying tokens somehow?

**Comment by starkillerOG** [comment]
@BodingClockchian Note that the whole AccesToken is only a hypothesis and I don't know if this is actually the case.

Besides creating a new account on the Motion Blinds Cloud I don't know how to update the tokens.

The error you provided: 'AccessToken error' is an error returned by the gateway itself, that means that there is eather something wrong in the firmware of the gateway that might require the cloud connection or something. Or you are just using the wrong key (from which the token is generated). Are you sure you are using the correct key?

**Comment by BodingClockchian** [comment]
@starkillerOG 
Yeah im using the correct key. I've been using it for a while now. Somehow im now able to control the blinds (after readding bridge again) with python (this repo and HASSIO) but not with the app anymore. Device does not exist, doesnt belong to user errors when adding a new device.

I've checked the AccessToken, its the same. There's something f**cking things up, not sure where to look next.
Also send this issue to Coullise B.V., they might have an idea. 

Thanks for your help so far!

**Comment by starkillerOG** [comment]
@BodingClockchian I checked at my gateway, and when I unplug my internet from my router, the motion blinds keep working just fine through HomeAssistant.

So the cloud connection is not required to check the accestokens.

I also tested what happens if I use the wrong key, and then I get exactly the same error message as you get.
Therefore I would advise to check the key once more from the motion app, it might have changed since you also sad that you deleted the gateway and re-added it several times.

**Comment by BodingClockchian** [comment]
@starkillerOG 
In the meantime I've received a new bridge from Coullise. They said my current one does have a problem that could be fixed. (Not sure how they would know this but sure).
(Api key is the same btw, I've checked)

**Comment by starkillerOG** [comment]
Intresting, so probably it is something in the firmware.
Good to hear that you are back up and running with your new gateway.

Schould I close this issue then?

**Comment by BodingClockchian** [comment]
Yeah, I guess its the firmware. Thanks for looking into this with me, really appreciate it. ;)

**Comment by starkillerOG** [comment]
@BodingClockchian I just got the beta version of the new firmware, I got the same errors as you did.
I now updated this library to work with the new gateway firmware, so it is now safe to use the new firmware.
